/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Excluir;

import DAO.CadastrarusuDAO;
import DAO.Conexao;
import Modelo.cadastrarusu;

import Principal.Menu2;
import Visao.Cadastrar.Cadastrarusu;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius de Almeida
 */
public class ExcluirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirUsario
     */
    public ExcluirUsuario() {
        initComponents();
        setSize(500, 400);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tdcod = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        tfnome = new javax.swing.JTextField();
        tfcpf = new javax.swing.JTextField();
        tftelefone = new javax.swing.JTextField();
        tflogin = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        w = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Login");

        tdcod.setEditable(false);
        tdcod.setBackground(new java.awt.Color(204, 204, 204));
        tdcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdcodActionPerformed(evt);
            }
        });

        tfemail.setEditable(false);
        tfemail.setBackground(new java.awt.Color(204, 204, 204));
        tfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfemailActionPerformed(evt);
            }
        });

        tfnome.setEditable(false);
        tfnome.setBackground(new java.awt.Color(204, 204, 204));

        tfcpf.setEditable(false);
        tfcpf.setBackground(new java.awt.Color(204, 204, 204));

        tftelefone.setEditable(false);
        tftelefone.setBackground(new java.awt.Color(204, 204, 204));

        tflogin.setEditable(false);
        tflogin.setBackground(new java.awt.Color(204, 204, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Excluir Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 10, 270, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("NOME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 60, 22);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("CÓDIGO DO USUARIO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 70, 193, 22);
        getContentPane().add(w);
        w.setBounds(240, 70, 190, 30);
        getContentPane().add(nome);
        nome.setBounds(110, 110, 320, 30);

        jToggleButton2.setBackground(new java.awt.Color(0, 255, 0));
        jToggleButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToggleButton2.setText("Excluir");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(90, 220, 100, 40);

        jToggleButton3.setBackground(new java.awt.Color(0, 51, 255));
        jToggleButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToggleButton3.setText("Voltar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(300, 220, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/04.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdcodActionPerformed

    private void tfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfemailActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
       new Menu2().setVisible(true);
       dispose();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

               
   String codi = w.getText();
   String Nome = nome.getText();
   
   
     Connection con = Conexao.AbrirConexao();
     CadastrarusuDAO sql = new CadastrarusuDAO(con);
     cadastrarusu a = new cadastrarusu();
    if(codi.equals("")){
    }else{
    JOptionPane.showMessageDialog(null, "Deseja realmente excluir o usuario (" +Nome+")?","lojadecd",JOptionPane.INFORMATION_MESSAGE);
   
    int cod = Integer.parseInt(codi);
    
    
    a.setcodigo(cod);
    

    sql.Inserir_ExcluirUsuario(a);
    
    Conexao.FecharConexao(con);
    new ExcluirUsuario().setVisible(true);
        dispose();
}
        
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField tdcod;
    private javax.swing.JTextField tfcpf;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tflogin;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextField tftelefone;
    private javax.swing.JTextField w;
    // End of variables declaration//GEN-END:variables
}
